### ISSUE TITLE
Chai and sinon required after upgrade from 0.3.2 -> 0.3.5

### ISSUE THREAD

**Issue by bengeorge** [mlison/protractor-jasmine2-screenshot-reporter#94]
From 0.3.3 chai and sinon are required.  I tried deleting node_modules / npm prune etc. before each time I tried to be sure.  0.3.2 is fine.

Example error below.

```
[15:40:28] E/launcher - Error: Error: Cannot find module 'chai'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (blah\node_modules\protractor-jasmine2-screenshot-reporter\test\index.spec.js:3:29)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

```

**Comment by mlison** [comment]
Ah, those must be missing as dev dependencies - but I think that should only be when you run tests, yes?

**Comment by bengeorge** [comment]
I am pulling in pj2sr as a devDependencies, and when I run my protractor
tests I get the error regarding chai and sinon.

https://github.com/mlison/protractor-jasmine2-screenshot-reporter/commit/89c5f72b7c9929c70ccd890ddb126f566c70ad08#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

This is where it was added, but this looks fine, chai is only required in
tests.
